import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  formContainer: {
    margin: '3rem auto',
    width: '70%',
    boxShadow:
      '0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 7px 20px 0 rgba(0, 0, 0, 0.2)',
    borderRadius: '10px',
    height: '510px',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    [theme.breakpoints.down('xs')]: {},
  },

  contentLeft: {
    backgroundColor: '#fff',
    borderRadius: '10px 0 0 10px',
    position: 'relative',
    [theme.breakpoints.down('xs')]: {},
  },
  formImg: {
    width: '60%',
    height: '50%',
    position: 'absolute',
    top: '55%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  formHeading: {
    color: '#846F75',
    display: 'flex',
    justifyContent: 'center',
    fontSize: '2rem',
    marginTop: '5rem',
  },
  contentRight: {
    borderRadius: '0 10px 10px 0',
    position: 'relative',
    background: '#F9B087',
  },
  form: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '90%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formTitle: {
    fontSize: '1.4rem',
    textAlign: 'center',
    width: '80%',
    marginBottom: '1rem',
    marginTop: '-1.8rem',
    color: '#846F75',
  },
  formInputs: {
    marginBottom: '0.8rem',
    width: '80%',
  },
  formInputsP: {
    fontSize: '0.8rem',
    marginTop: '0.5rem',
    color: '#846F75',
  },
  formLabel: {
    display: 'inline-block',
    fontSize: '1.1rem',
    marginBottom: '6px',
    color: '#846F75',
  },
  formInput: {
    display: 'block',
    paddingLeft: '10px',
    outline: 'none',
    borderRadius: '2px',
    height: '40px',
    width: '100%',
    border: 'none',
    '&::placeholder': {
      color: '#',
      fontSize: '12px',
    },
    '&:focus::placeholder': {
      transition: 'all 0.3s',
      color: 'transparent',
      fontSize: '12px',
    },
  },
  formInputBtn: {
    width: '83%',
    height: '50px',
    marginTop: '15px',
    marginLeft: '14px',
    borderRadius: '2px',
    background: '#846F75',
    outline: 'none',
    border: 'none',
    color: '#fff',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.3s',
    '&:hover': {
      background: 'white',
      color: '#846F75',
    },
  },
  formInputLogin: {
    fontSize: '0.8rem',
    marginTop: '10px',
    color: '#846F75',
    width: '80%',
    textAlign: 'center',
  },
  formInputLoginLink: {
    textDecoration: 'none',
    color: '#846F75',
    fontWeight: 600,
  },
}));
